server:
  port: 9393

management:
  contextPath: /management

info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"

security:
  basic:
    enabled: false

spring:
  application:
    name: spring-cloud-dataflow-server-swarm
  cloud:
    config:
      uri: http://localhost:8888
    dataflow:
      applicationProperties:
        stream:
          spring:
            cloud:
              stream:
                kafka:
                  binder:
                    brokers: 192.168.99.100:9092
                    zkNodes: 192.168.99.100:2181

# Configuration options for the deployer. The "environmentVariables" property should be set in
# the server's ConfigMap when the server is deployed:
#spring:
#  cloud:
#    deployer:
#      swarm:
#        createLoadBalancer: false
#        environmentVariables: ''

# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is 
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka 
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#---
#spring:
#  cloud:
#     config:
#        discovery:
#           enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
